### ISSUE TITLE
Crash Required value 'playlist' missing at

### ISSUE THREAD

**Issue by pio2398** [siper/Youamp#166]
Crash after switch to artists. navidrome server.
```
time: 1718016193051
msg: u4.n: Required value 'playlist' missing at $.playlists
stacktrace: u4.n: Required value 'playlist' missing at $.playlists
	at v4.e.e(SourceFile:64)
	at ru.stersh.youamp.core.api.PlaylistsResponse_PlaylistsDataJsonAdapter.b(SourceFile:64)
	at v4.a.b(SourceFile:16)
	at ru.stersh.youamp.core.api.PlaylistsResponseJsonAdapter.b(SourceFile:32)
	at v4.a.b(SourceFile:16)
	at P5.c.e(SourceFile:32)
	at O5.D.d(SourceFile:56)
	at O5.A.b(SourceFile:5)
	at m5.g.run(SourceFile:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: Y4.h: [y0{Cancelling}@edeea9c, Dispatchers.Main.immediate]

```

Version: 1.0.0-alpha03

**Comment by siper** [comment]
Hello, thanks for you feedback. Please try version 1.0.0-alpha06. If it crashes again, give a feedback.

**Comment by pio2398** [comment]
Alpha07 work without problems. Thanks
